name = "boxland_3d_thing"
version = "0.0.0"
license = "GPL-2.0-only"
author = "jordan4ibanez"
maintainer = "jordan4ibanez"
copyright = "Copyright 2024, jordan4ibanez"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

# This is just for fedora.
link = ["glfw"]

[dependencies]
forthread = { git = "https://github.com/jordan4ibanez/forthread" }
uuid_now = { git = "https://github.com/jordan4ibanez/uuid_now" }
hashmap_f90 = { git = "https://github.com/jordan4ibanez/hashmap_f90" }
fortran_vector = { git = "https://github.com/jordan4ibanez/fortran_vector" }
files_f90 = { git = "https://github.com/jordan4ibanez/files_f90" }
string_f90 = { git = "https://github.com/jordan4ibanez/string_f90" }
constants_f90 = { git = "https://github.com/jordan4ibanez/constants_f90" }
forterm = { git = "https://github.com/jordan4ibanez/forterm" }
fglm = { git = "https://github.com/jordan4ibanez/fglm" }

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
